# different version supports amongst other things different keys -
# further informations on:
# https://docs.docker.com/compose/compose-file/compose-versioning/
# and for documentation of available keys for service configuration:
# https://docs.docker.com/compose/compose-file/#service-configuration-reference
version: '3'

services:
  php-fpm:
    build:
      # context points to (local) folder which contains the Dockerfile for this container
      context: ./php-fpm
    volumes:
      #mount volumes -> HOST-Path:CONTAINER-Path
      - ../public:/var/www

  web:
    build:
      context: ./web
    volumes:
      - ../public:/var/www
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/sites/:/etc/nginx/sites-available
      - ./web/conf.d/:/etc/nginx/conf.d
    #set a dependency between 'web' and 'php-fpm'
    depends_on:
      - php-fpm
    #port mapping from HOST : CONTAINER
    ports:
      - "80:80"
      - "443:443"
    #command: [nginx-debug, '-g', 'daemon off;']
    #command: [nginx-debug]

  mysql:
    build:
      context: ./mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    #set environment vars for mysql server              !!! change passwords !!!
    environment:
      - MYSQL_DATABASE=mysqldb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=docker
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data.sql:/docker-entrypoint-initdb.d/data.sql
      # decomment the following line to store DB persistant on local ../data/mysql folder
      # - ../data/mysql:/var/lib/mysql

  #
  # Optional Service: decomment this section to enable phpMyAdmin
  #
  # phpmyadmin:
  #   build:
  #     context: ./phpmyadmin
  #   # Map port 8181 on the host to port 80 inside the container
  #   ports:
  #     - "8181:80"
  #   # Pass a list of environment variables to the container - set "mysql" container as host
  #   environment:
  #     - "PMA_HOST=mysql"
  #   # Wait for "mysql" container to start first
  #   depends_on: 
  #     - mysql
